<?php
/**
 * 返程补贴
 *
 * User: tuan
 * Date: 14/11/29
 * Time: 13:24
 */
class BackSubsidyCalculator  extends Calculator {
	private $cityId;
	private $distance;
	private  $orderType;

	function __construct($cityId, $distance, $orderType)
	{
		$this->cityId = $cityId;
		$this->distance = $distance;
		$this->orderType = $orderType;
	}


	function validator()
	{
		return true; // TODO: Change the autogenerated stub
	}

	public function toString()
	{
		return parent::toString(); // TODO: Change the autogenerated stub
	}

	protected function getFee()
	{
		$fee = 0.00;
		$orderType = $this->orderType;
		$cityId    = $this->cityId;
		if(FinanceConstants::ORDER_TYPE_DAYTIME == $orderType){
            $daytime_type = CityConfigService::dayTimeStatus($cityId);
			if($daytime_type && isset(Yii::app()->params['daytime_price'][$daytime_type])){
				$day_time_data = Yii::app()->params['daytime_price'][$daytime_type];
				EdjLog::info('config --- '.json_encode($day_time_data));
				$returnFee = $day_time_data['return_fee'];
				$distanceCondition = $returnFee['min_distance'];
				$unitPrice = $returnFee['fee'];
				$distance = $this->distance;
				if($distance > $distanceCondition){
					$fee = ceil($distance) * $unitPrice;
				}
			}
		}
		return $fee;
	}
}